name: Bump Version

on:
  workflow_dispatch:
    inputs:
      bump:
        required: false
        description: Version Bump (major, minor, patch + alpha, beta, rc, post, and dev)
        type: string
        default: 'patch'

jobs:
  bump:
    name: Version Bump
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # store for use with reusable actions
    outputs:
      VERSION: "${{ steps.version.outputs.VERSION }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Version Bump
        id: version
        uses: rehborn/uv-version-bump-action@main
        with:
          bump: ${{ inputs.bump }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: bump
    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      version: ${{ needs.bump.outputs.VERSION }}

  publish:
    needs:
      - bump
      - build
    permissions:
      packages: write
      contents: write
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      version: ${{ needs.bump.outputs.VERSION }}

  release:
    needs:
      - bump
      - build
    permissions:
      packages: write
      contents: write
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      version: ${{ needs.bump.outputs.VERSION }}

  notify:
    name: Send Notifications
    runs-on: ubuntu-latest
    needs:
      - bump
      - release
    steps:
      - name: Discord
        run: |
          RELEASE_URL="https://github.com/${{ github.repository}}/releases/tag/${{ needs.bump.outputs.VERSION }}"
          BODY="[${{ github.repository}} **v${{ needs.bump.outputs.VERSION }}**](${RELEASE_URL}) Released"
          curl -H "Content-Type: application/json" -d "{\"content\": \"$BODY\"}" ${{ secrets.DISCORD_WEBHOOK_URL }}
